plugins:
  postal_enabled:
    default: false
    client: true
  postal_endpoint:
    default: "https://your-postal-server.com/api/v1/send/message"
    description: "Full URL to the Postal send endpoint"
  postal_api_key:
    default: ""
    secret: true
    description: "Your Postal Server API Key"
